### ISSUE TITLE
`ended` event not firing

### ISSUE THREAD

**Issue by Abdullah0991** [vmudigal/ngx-audio-player#66] opened 2020-06-18 19:08 UTC
Hi,
Using this lib version 9.1.0 in Angular version 9.0.0, the `ended` event not fired when the player finish playing.

Test done on Chrome and FireFox browsers, `*.wav` and `*.mp3` formats.

```
<mat-basic-audio-player *ngIf="currentMsg.isAudioCall" [audioUrl]="currentMsg.rawData"
                        [title]="'Audio Message'" [autoPlay]="true"
                        (ended)="playAudioFileEnded($event)"></mat-basic-audio-player>
```

**Comment by vmudigal** [comment] 2020-06-18 22:28
Hi,

Could you please try to use (trackEnded)="playAudioFileEnded($event)" instead of (ended)="playAudioFileEnded($event)"?

I will update the document soon.

Thanks.

Best Regards,
Vijayendra

**Comment by goutick** [comment] 2020-06-21 06:32
Hi,
First of all thanks for writing this Audio Player!! :) 

I had already added  (trackEnded) = "TrackEnded($event)" still it did not fire the _TrackEnded($event)_ and it did not play next song automatically.

Please find the attached images : 

![Screen Shot 2020-06-21 at 11 48 04 AM](https://user-images.githubusercontent.com/26975317/85218235-ef17fa80-b3b5-11ea-9704-4f3b60d6e4f6.png)

![Screen Shot 2020-06-21 at 11 47 52 AM](https://user-images.githubusercontent.com/26975317/85218236-f0e1be00-b3b5-11ea-99a6-ad848fa0bdab.png)

![Screen Shot 2020-06-21 at 11 57 09 AM](https://user-images.githubusercontent.com/26975317/85218313-c8a68f00-b3b6-11ea-9d4b-75f6e055447d.png)

**Comment by Abdullah0991** [comment] 2020-06-21 09:39
> Hi,
> First of all thanks for writing this Audio Player!! :)
> 
> I had already added (trackEnded) = "TrackEnded($event)" still it did not fire the _TrackEnded($event)_ and it did not play next song automatically.
> 
> Please find the attached images :
> 
> ![Screen Shot 2020-06-21 at 11 48 04 AM](https://user-images.githubusercontent.com/26975317/85218235-ef17fa80-b3b5-11ea-9704-4f3b60d6e4f6.png)
> 
> ![Screen Shot 2020-06-21 at 11 47 52 AM](https://user-images.githubusercontent.com/26975317/85218236-f0e1be00-b3b5-11ea-99a6-ad848fa0bdab.png)
> 
> ![Screen Shot 2020-06-21 at 11 57 09 AM](https://user-images.githubusercontent.com/26975317/85218313-c8a68f00-b3b6-11ea-9d4b-75f6e055447d.png)

Same!! not working.

**Comment by Abdullah0991** [comment] 2020-06-22 11:07
> > Hi,
> > First of all thanks for writing this Audio Player!! :)
> > I had already added (trackEnded) = "TrackEnded($event)" still it did not fire the _TrackEnded($event)_ and it did not play next song automatically.
> > Please find the attached images :
> > ![Screen Shot 2020-06-21 at 11 48 04 AM](https://user-images.githubusercontent.com/26975317/85218235-ef17fa80-b3b5-11ea-9704-4f3b60d6e4f6.png)
> > ![Screen Shot 2020-06-21 at 11 47 52 AM](https://user-images.githubusercontent.com/26975317/85218236-f0e1be00-b3b5-11ea-99a6-ad848fa0bdab.png)
> > ![Screen Shot 2020-06-21 at 11 57 09 AM](https://user-images.githubusercontent.com/26975317/85218313-c8a68f00-b3b6-11ea-9d4b-75f6e055447d.png)
> 
> Same!! not working.

Sorry, It worked in FF but doesn't in Chrome.

**Comment by vmudigal** [comment] 2020-06-23 18:53
> > Same!! not working.
> 
> Sorry, It worked in FF but doesn't in Chrome.

Working in Chrome Version 83.0.4103.97. Could you please provide more info?
Also, could you please check for "Browser compatibility" at https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event

**Comment by Abdullah0991** [comment] 2020-06-23 19:10
> Working in Chrome Version 83.0.4103.97. Could you please provide more info?
> Also, could you please check for "Browser compatibility" at https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event

I already have Chrome v83.0.4103.106, and now I updated it to v83.0.4103.116 and still not working.

For "Browser compatibility", I checked it and it says it fully compatible from v3.

**Comment by vmudigal** [comment] 2020-06-23 19:17
Looks like this is hard to replicate. I will check, meantime if anyone figures out the root cause, please share.

<img width="853" alt="Screenshot 2020-06-24 at 00 45 07" src="https://user-images.githubusercontent.com/1531622/85448328-34098000-b5b4-11ea-8e08-51c1ad7b8aba.png">

**Comment by goutick** [comment] 2020-06-24 09:57
Thanks for your reply.

My PlayList = [
{
title: "Test.mp3",
link:"https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3"
},
{
title:"2.mp3"
link : "http://localhost:8080/GetSong/Song=2.mp3"
}]

Can you please try using the same link _("https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3")_

For the second song I was sending song from a Node Api : 
ex: http://localhost:8080/GetSong/Song=2.mp3

The above api will send song using : _response.sendFile("2.mp3")_

I'm not sure if this is caused the issue but i thought it might help.

:)

**Comment by Oliverq755** [comment] 2020-07-06 19:02
The same issue facing here too. I checked it out in both FF and Chrome, None worked. Looking forward for the faster fix for this issue.

**Comment by angristan** [comment] 2020-07-15 15:50
I'm facing this too ! I didn't understand what I did wrong but it turns out the event is never fired:

![image](https://user-images.githubusercontent.com/11699655/87566631-980afa00-c6c3-11ea-9df0-12ae0f27e62a.png)

**Comment by angristan** [comment] 2020-07-15 16:09
I think it's because we expect the `ended` event to be fired when the track finished playing. 

If you fast-forward to the end, it will most likely not work for some reason. Try by playing the track from the beginning and let it play until the end: the event will fire.

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event:

> `ended` events fire when the media stream track's source permanently stops sending data on the stream. There are various ways this can happen, including:
> 
> There is no more data left to send.
> The user revoked the permissions needed for the data to be sent.
> The hardware generating the source data has been removed or ejected.
> A remote peer has permanently stopped sending data; pausing media does not generate an `ended` event.

So it **does** work (regardless of the browser), but it's not reliable :(

**Comment by vmudigal** [comment] 2020-09-05 20:14
It was a regression. Have fixed the issue on v8 and above.

**Closed by vmudigal** 2020-09-05 20:14 UTC
