### ISSUE TITLE
Feature request: Auto-replay option

### ISSUE THREAD

**Issue by Abdullah0991** [vmudigal/ngx-audio-player#68] opened 2020-06-21 09:47 UTC
Hi,

I know I can use the `trackEnded` event for auto-replay the track, but It will be more beautiful if this option added to the library, especially if you could also add a `button toggle` or `checkbox` control to control this option from the UI, the `toggle button` could be added besides the volume mute button.

Regards.

**Comment by vmudigal** [comment] 2020-06-23 18:40
duplicate of Auto Play Error #58

**Comment by Abdullah0991** [comment] 2020-06-23 19:25
Sorry, but what's the link between auto-**replay** and auto-**play** ?

**Comment by vmudigal** [comment] 2020-06-23 19:41
My bad, read it wrong. Sorry.

**Comment by vmudigal** [comment] 2020-06-23 21:07
Duplicate of Repeat/Loop function #47

**Closed by vmudigal** 2020-06-23 21:07 UTC
Labels: duplicate
